USE [Plexus]
GO
/****** Object:  StoredProcedure [dbo].[usp_RecoveriesLoad]    Script Date: 1/26/2018 7:32:59 AM ******/

UPDATE [App_Recoveries].dbo.EDC
SET NAME = 'NORM'
WHERE NAME = 'NORMB'

GO


/* BEFORE YOU ANALYZE THE CODE READ BELOW

The seciton of code below is for updating an existing TLN account on Plexus,

*/
  /*Declaring a cursor*/
   
  --DECLARE @ExistingLiveAccounts CURSOR;

  /*Cursor variables*/
 DECLARE @MPM_TLN_ACCT_NO VARCHAR(50)
 DECLARE @Status VARCHAR(50)
 DECLARE @CUST_NO BIGINT
 DECLARE @PRODUCT VARCHAR(50)
 DECLARE @DDA_ACCOUNT_NO VARCHAR(50)
 DECLARE @DDA_SUB_PROD_CDE VARCHAR(50) 
 DECLARE @TLN_TAKE_UP_DATE DATE
 DECLARE @TLN_LOAN_VALUE VARCHAR(50)
 DECLARE @TLN_INIT_FEE VARCHAR(50)
 DECLARE @TLN_TOTAL_AMT VARCHAR(50)
 DECLARE @AMT_REPAID VARCHAR(50)
 DECLARE @ARREARS VARCHAR(50)
 DECLARE @FORCE_PAY_DATE DATE
 DECLARE @TLN_REMAINING_AMT VARCHAR(50)
 DECLARE @ARREARS_DAYS VARCHAR(50)
 DECLARE @TLN_TAKEUP_SOURCE VARCHAR(50)
 DECLARE @RESIDUAL_ACC_NR VARCHAR(50)
 DECLARE @RisidualOpenDate Datetime 

  /*Variables to be used in the process below*/
 DECLARE @PROCESS_STATUS varchar(255)='ALLOCATED'
 DECLARE @DAYS_SINCE_TAKE_UP_BUSINESS int
 DECLARE @CURRENT_STATUS_CODE varchar(255)
 DECLARE @DAYS_IN_ARR_BUSINESS int
 DECLARE @DAYS_IN_ARR_CALENDAR int
 DECLARE @DAYS_SINCE_TAKE_UP int
 DECLARE @LAST_PMT_AMT numeric(19,2)
 DECLARE @LAST_PMT_DATE date
 DECLARE @LAST_UPDATE_DATE date
 DECLARE @PROGRESS_FLAG varchar(255)
 DECLARE @RECOVERY_WI_ID bigint
 DECLARE @RES_ACC_OPEN_DATE date
 DECLARE @ORIGINATING_QUEUE varchar(255)
 DECLARE @ACTION_TAKEN varchar(255)
 DECLARE @EVENT_TYPE_ID int =2
 DECLARE @WORK_ITEM_VERSION BIGINT
 DECLARE @USER_ID INT
 DECLARE @StatusID BIGINT
 DECLARE @Note Varchar(100)
 DECLARE @CREATED_DATE DATETIME = GETDATE()
 DECLARE @ALLOCATION_DATE DATETIME = GETDATE()
 DECLARE @ALLOCATION_REASON VARCHAR(20)
 DECLARE @ALLOCATION_TYPE VARCHAR(10)='1'
 DECLARE @tblRecoveryID TABLE (ID BIGINT)
 DECLARE @RecoveryID BIGINT
 DECLARE @RecordType varchar(20)
 DECLARE @DAYS_WITH_EDC INT= 0
 DECLARE @END_DATE DATETIME 
 DECLARE @StatusDesc VARCHAR(50) 
 DECLARE @EDC_ID BIGINT
 DECLARE @DETAIL VARCHAR(100)
 DECLARE @tblWorkItem_ID_Date TABLE (ID BIGINT,[DATE] DATETIME )
 DECLARE @WorkItemID BIGINT
 DECLARE @tlbWorkItemHistoryID  TABLE (ID BIGINT)
 DECLARE @WorkItemHistoryID INT
 DECLARE @BusinessAreaID BIGINT 
 DECLARE @CreditMessageID BIGINT 
 DECLARE @tblCreditMessageID TABLE (ID BIGINT)
 DECLARE @CREDIT_WI_ID BIGINT
 DECLARE @tblCaseID TABLE (ID BIGINT)
 DECLARE @UserID BIGINT
 DECLARE @WORK_ITEM_TYPE_ID BIGINT
 DECLARE @QUEUE_ID BIGINT
 DECLARE @WORK_ITEM_STATE_ID BIGINT
 DECLARE @VERSION INT
 DECLARE @PRODUCT_CODE VARCHAR(5)='TLN'
 DECLARE @OpenCloseStatus VARCHAR(10)
 DECLARE @Action varchar(25);
 DECLARE @FLAG_CLOSED bit
 DECLARE @QDesc VARCHAR(50) 
 DECLARE @CLOSURE_PROCESSED BIT=0
/* BEFORE YOU ANALYZE THE CODE READ BELOW

The seciton of code below is for Inserting new  TLN account on Plexus,

*/
  /*Declaring a cursor*/

  DECLARE @NewLiveAccounts CURSOR;


   /*Initiating a cursor*/
  SET @NewLiveAccounts= CURSOR FOR
  SELECT [CUST_NO],[PRODUCT],[MPM_TLN_ACCT_NO],[DDA_ACCOUNT_NO],[DDA_SUB_PROD_CDE]
      ,CONVERT(DATE,[TLN_TAKE_UP_DATE], 105)[TLN_TAKE_UP_DATE],[TLN_LOAN_VALUE],[TLN_INIT_FEE],[TLN_TOTAL_AMT],[AMT_REPAID]
      ,[ARREARS],CONVERT(DATE,[FORCE_PAY_DATE], 105)[FORCE_PAY_DATE],[TLN_REMAINING_AMT],[ARREARS_DAYS],[TLN_TAKEUP_SOURCE],[STATUS]
  FROM [App_Recoveries].[Staging].[ImportTLNLive]
  WHERE [MPM_TLN_ACCT_NO] NOT IN
  (SELECT 
      [MPM_ACC_NO]
    
  FROM [App_Recoveries].[dbo].[CREDIT_MESSAGE]
  ) 

 /*open the  cursor*/
  OPEN  @NewLiveAccounts;

FETCH NEXT FROM @NewLiveAccounts INTO @CUST_NO,@PRODUCT,@MPM_TLN_ACCT_NO,@DDA_ACCOUNT_NO,@DDA_SUB_PROD_CDE,
									 @TLN_TAKE_UP_DATE,@TLN_LOAN_VALUE,@TLN_INIT_FEE,@TLN_TOTAL_AMT,@AMT_REPAID,
									 @ARREARS,@FORCE_PAY_DATE,@TLN_REMAINING_AMT,@ARREARS_DAYS,@TLN_TAKEUP_SOURCE,
									 @Status

 ------------------/*New Accounts*/---------------------------------------------------------
WHILE @@FETCH_STATUS = 0
BEGIN

  /*Other variables*/
SET @BusinessAreaID =(SELECT [ID] FROM [Plexus].[dbo].[BUSINESS_AREA] WHERE NAME ='CRV')
SET @WorkItemID =(SELECT  [WORK_ITEM_ID] FROM [App_Recoveries].[dbo].[CREDIT_MESSAGE] WHERE MPM_ACC_NO =@MPM_TLN_ACCT_NO)
SET @StatusDesc       = CASE WHEN @Status ='GWL' THEN 'ALLOCATED_GWL_MI'
                             WHEN @Status ='FARM' THEN 'ALLOCATED_FARM_MI'
							 WHEN @Status ='DEC' THEN 'DECEASED' 
							 WHEN @Status = 'SEQ' THEN 'SEQUESTRATED'
							 WHEN @Status = 'DRC' THEN 'DEBT_REVIEW'
							 WHEN @Status = 'CLD' THEN 'ACC_BALANCE_ZERO'
							 WHEN @Status ='NORM' THEN 'REALLOCATE_NORMB'
							 WHEN @Status = 'HAMP' THEN 'ALLOCATED_HAMP_MI'
							 END

SET @QDesc = CASE WHEN @Status ='GWL' THEN 'PRE_LIT_GWL'
                             WHEN @Status ='FARM' THEN 'PRE_LIT_FARM'
							 WHEN @Status ='DEC' THEN 'DECEASED' 
							 WHEN @Status = 'SEQ' THEN 'SEQUESTRATED'
							 WHEN @Status = 'DRC' THEN 'DEBT_REVIEW'
							 WHEN @Status = 'CLD' THEN 'CLOSED'
							 WHEN @Status ='NORM' THEN 'OUTS_NORMB'
							 WHEN @Status = 'HAMP' THEN 'PRE_LIT_HAMP'
							 END

SET @StatusID = (SELECT  [ID] FROM [Plexus].[dbo].[STATUS] WHERE NAME =@StatusDesc AND BUSINESS_AREA_ID=@BusinessAreaID AND [DESCRIPTION] IS NOT null)
SET @EDC_ID = (CASE WHEN @Status ='GWL' THEN 1 WHEN @Status ='FARM' THEN 2 ELSE 0 END)
SET @DETAIL ='Work item''s status has been changed to [' + @StatusDesc + ' ] by initial ETL load'
SET @RECOVERY_WI_ID = (SELECT MAX([RECOVERY_WI_ID])+1 AS [RECOVERY_WI_ID]  FROM [App_Recoveries].[dbo].[RECOVERIES])
SET @WORK_ITEM_VERSION= 0
SET @Note = (SELECT TOP 1 [DESCRIPTION]FROM [Plexus].[dbo].[STATUS]WHERE NAME =@StatusDesc)
SET @USER_ID = (SELECT ID FROM dbo.[USER] WHERE BUSINESS_AREA_ID =@BusinessAreaID AND USER_TYPE_ID=3)
SET @RecoveryID =(SELECT [RECOVERY_ID] FROM [App_Recoveries].[dbo].[CREDIT_MESSAGE] WHERE MPM_ACC_NO =@MPM_TLN_ACCT_NO)
SET @UserID =(SELECT [ID] FROM [Plexus].[dbo].[USER]WHERE USERNAME LIKE '%crv%' AND BUSINESS_AREA_ID =@BusinessAreaID)
SET @WORK_ITEM_TYPE_ID =( SELECT  ID FROM [Plexus].dbo.WORK_ITEM_TYPE WHERE NAME='RECOVERIES_TLN')
SET @QUEUE_ID =(SELECT TOP 1 [ID] FROM [Plexus].[dbo].[QUEUE] WHERE NAME =@QDesc and BUSINESS_AREA_ID=@BusinessAreaID)
SET @WORK_ITEM_STATE_ID =(SELECT [ID]  FROM [Plexus].[dbo].[WORK_ITEM_STATE]  WHERE [STATE] = 'ALLOCATED')
SET @VERSION =1
SET @OpenCloseStatus ='OPEN'
Set @Action = 'CREATE'
Set @FLAG_CLOSED = 0
SET @ALLOCATION_REASON =     CASE WHEN @Status ='NORM' THEN 'Outsource'
								  WHEN @Status = 'HAMP' THEN '2nd Allocation'
							      ELSE '1st Allocation'
						     END




------INSERT INTO RECOVERIES-------------------------------------------------------------
 INSERT INTO [App_Recoveries].[dbo].[RECOVERIES]
([CREATED_DATE],[PROCESS_STATUS],[DAYS_SINCE_TAKE_UP_BUSINESS],[CURRENT_STATUS_CODE],[DAYS_IN_ARR_BUSINESS],[DAYS_IN_ARR_CALENDAR],[DAYS_SINCE_TAKE_UP]
 ,[LAST_PMT_AMT],[LAST_PMT_DATE],[LAST_UPDATE_DATE],[PROGRESS_FLAG],[RECOVERY_WI_ID],[RESIDUAL_ACC_NR],[RES_ACC_OPEN_DATE],[ORIGINATING_QUEUE]
 ,[ACTION_TAKEN])

OUTPUT Inserted.ID INTO  @tblRecoveryID(ID)
VALUES
(      @CREATED_DATE, @PROCESS_STATUS, @DAYS_SINCE_TAKE_UP_BUSINESS,@CURRENT_STATUS_CODE,@DAYS_IN_ARR_BUSINESS,
      @DAYS_IN_ARR_CALENDAR,@DAYS_SINCE_TAKE_UP,@LAST_PMT_AMT,@LAST_PMT_DATE,@LAST_UPDATE_DATE,@PROGRESS_FLAG,
      @RECOVERY_WI_ID,@RESIDUAL_ACC_NR,@RES_ACC_OPEN_DATE,@ORIGINATING_QUEUE,@ACTION_TAKEN
)
SET @RecoveryID = (SELECT ID FROM @tblRecoveryID)
---------------------End of INSERT INTO RECOVERIES

------------INSERT INTO CREDIT MESSAGE-----------------------------------------------


 INSERT INTO [App_Recoveries].[dbo].[CREDIT_MESSAGE]
(CREATED_DATE,[UCN],[MPM_ACC_NO],[DDA_ACC_NO],[DDA_SUB_PRODUCT],[TAKEUP_DATE],
[TAKEUP_AMOUNT],[TAKEUP_FEE],[TAKEUP_TOTAL],[AMOUNT_REPAID],[ARREARS],[STATUS],
[FORCE_PAY_DATE],[BALANCE],[DAYS_IN_ARREARS],[TAKEUP_CHANNEL],RECOVERY_ID,[PRODUCT_CODE],[Action],[FLAG_CLOSED]
)
OUTPUT Inserted.ID INTO  @tblCreditMessageID(ID)
VALUES
(GETDATE(),@CUST_NO,@MPM_TLN_ACCT_NO,@DDA_ACCOUNT_NO,@DDA_SUB_PROD_CDE,@TLN_TAKE_UP_DATE,
@TLN_LOAN_VALUE,@TLN_INIT_FEE,@TLN_TOTAL_AMT,@AMT_REPAID,@ARREARS,@OpenCloseStatus,@FORCE_PAY_DATE,
@TLN_REMAINING_AMT,@ARREARS_DAYS,@TLN_TAKEUP_SOURCE,@RecoveryID,@PRODUCT_CODE,@Action,@FLAG_CLOSED
)
SET @CreditMessageID = (SELECT ID FROM @tblCreditMessageID)

--------------------END OF INSERT INTO CREDIT MESSAGE------------------------------------


 INSERT INTO [dbo].[WORK_ITEM]
 (
      [WORK_ITEM_TYPE_ID],[STATUS_ID],[QUEUE_ID],[CREATE_DATE],[CREATED_BY_USER_ID],[LAST_ACTIVITY_DATE]
      ,[LAST_ACTIVITY_BY_USER_ID],[WORK_ITEM_STATE_ID],[DESCRIPTION],[VERSION]
 )
 OUTPUT Inserted.ID,Inserted.CREATE_DATE INTO  @tblWorkItem_ID_Date(ID,[Date])

 VALUES
 (   @WORK_ITEM_TYPE_ID,@StatusID,@QUEUE_ID ,@CREATED_DATE , @UserID ,   
    @CREATED_DATE,@UserID,@WORK_ITEM_STATE_ID,@StatusDesc,@VERSION
 )


 SET @WorkItemID =  (SELECT ID FROM @tblWorkItem_ID_Date) 
-------END----------------------------------------

----SET RECOVERIES WI ID

UPDATE App_Recoveries.dbo.RECOVERIES
SET RECOVERY_WI_ID=@WorkItemID
WHERE ID=@RecoveryID
----

---UPDATE CREDIT MESSAGE----
UPDATE [App_Recoveries].dbo.CREDIT_MESSAGE
SET WORK_ITEM_ID= (SELECT ID FROM @tblWorkItem_ID_Date) 
WHERE ID=@CreditMessageId
----END-----------------


 ----Insert WorkItem History----------
   INSERT INTO WORK_ITEM_HISTORY 
  ([DETAIL],DATE_TIME,[WORK_ITEM_ID],[WORK_ITEM_VERSION],[USER_ID],[EVENT_TYPE_ID]) 
   OUTPUT Inserted.ID INTO  @tlbWorkItemHistoryID(ID)
   VALUES 
  ( @DETAIL,@CREATED_DATE,@WorkItemID,@WORK_ITEM_VERSION,@USER_ID,@EVENT_TYPE_ID)
  
  SET @WorkItemHistoryID =(SELECT ID FROM @tlbWorkItemHistoryID)


  ----END OF WorkItem History------------------

----Insert INTO  WORKITEM HISTORY NOTE------------
  INSERT INTO WORK_ITEM_HISTORY_NOTE
  ([WORK_ITEM_HISTORY_ID],[NOTE])
  VALUES (@WorkItemHistoryID,@Note)
-----END OF WORKITEM HISTORY NOTE----------

-----INSERT ALLOCATION--------------

  IF (SELECT [ID] FROM [App_Recoveries].[dbo].[EDC] WHERE NAME= @Status) IS NOT NULL
  BEGIN
   INSERT INTO [App_Recoveries].[dbo].ALLOCATION
	 ([CREATED_DATE],[ALLOCATION_DATE],[ALLOCATION_REASON],[ALLOCATION_TYPE]  ,[EDC_ID]
	   ,[RECOVERY_ID],[DAYS_WITH_EDC],[END_DATE],[CLOSURE_PROCESSED]
	  )

	VALUES
	(
		@CREATED_DATE,@ALLOCATION_DATE,@ALLOCATION_REASON,@ALLOCATION_TYPE,@EDC_ID
		,@RecoveryID,@DAYS_WITH_EDC,@END_DATE,@CLOSURE_PROCESSED
	)
 END

 ----INSERT INTO DECEASED ------------
 IF @Status = 'DEC'
 BEGIN
 INSERT INTO App_Recoveries.[dbo].[DECEASED] ([CREATED_DATE],[RECOVERIES_ID],[AWAIT_EXEC_INFO],[CLAIM_LODGED],
                                             [DEATH_CERT_UPLOADED],[DEATH_CONFIRMED],[EXEC_CONFIRM],[RISK_CAT_UPDATED],[EXT_TRACING_CONFIRM])
 VALUES (@CREATED_DATE,@RecoveryID,0,0,0,0,0,0,0)
 END
 ---------------------------------------------

 ---INSERT INTO [dbo].[SEQUESTRATED]
 IF @Status ='SEQ'
 BEGIN
 INSERT INTO App_Recoveries.dbo.SEQUESTRATED( CREATED_DATE,RECOVERIES_ID,[AWAIT_TRUSTEE_INFO],[CLAIM_LODGED],[COURT_ORDER_UPLOADED],
                                            [EXT_TRACING_CONFIRM],[RES_ACC_OPEN],[RISK_CAT_UPDATED],[SEQ_CONFIRMED], [TRUSTEE_CONFIRM]
											)
 VALUES (@CREATED_DATE,@RecoveryID,0,0,0,0,0,0,0,0)
 END
 ----

 DELETE @tblCreditMessageID
 DELETE @tblRecoveryID
 DELETE @tblWorkItem_ID_Date
 DELETE @tlbWorkItemHistoryID
 
FETCH NEXT FROM @NewLiveAccounts INTO @CUST_NO,@PRODUCT,@MPM_TLN_ACCT_NO,@DDA_ACCOUNT_NO,@DDA_SUB_PROD_CDE,
									 @TLN_TAKE_UP_DATE,@TLN_LOAN_VALUE,@TLN_INIT_FEE,@TLN_TOTAL_AMT,@AMT_REPAID,
									 @ARREARS,@FORCE_PAY_DATE,@TLN_REMAINING_AMT,@ARREARS_DAYS,@TLN_TAKEUP_SOURCE,
									 @STATUS
END

CLOSE @NewLiveAccounts   
DEALLOCATE @NewLiveAccounts
-------------------------------------------------------------------------------------------------





